plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.authnza'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

allprojects {
    group = 'com.platform'
    version = '1.0.0-SNAPSHOT'
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.7"
        }
    }

    dependencies {
//        compileOnly 'org.projectlombok:lombok'
//        annotationProcessor 'lombok'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
    }
}
repositories {
	mavenCentral()
}

//dependencies {
////	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
//	implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
//	implementation 'org.springframework.boot:spring-boot-starter-web'
//	developmentOnly 'org.springframework.boot:spring-boot-devtools'
////	runtimeOnly 'com.mysql:mysql-connector-j'
//	testImplementation 'org.springframework.boot:spring-boot-starter-test'
//	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
//}

tasks.named('test') {
	useJUnitPlatform()
}
