plugins {
    id 'java-library'
}

dependencies {
    // Jackson for DTOs and event serialization
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    compileOnly 'org.springframework.boot:spring-boot-starter-data-jdbc'


    // Validation annotations (@NotBlank, @NotNull, etc.)
    implementation 'org.springframework.boot:spring-boot-starter-validation'
}