server:
  port: 8082

spring:
  application:
    name: auth-iam-service
  
  data:
    redis:
      host: localhost
      port: 6379

app:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/auth-master?createDatabaseIfNotExist=true
      username: root
      password: sjain@123
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    com.authenza.iam: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
